### ISSUE TITLE
Bestes Vorgehen zum Nachbauen?

### ISSUE THREAD

**Issue by UweKeim** [jakiss/Radmesser#1]
Habe Deine zwei PDFs überflogen, weil bei uns in Eislingen einer der Grünen vorgeschlagen hat, das nachzubauen.

Was wäre denn ein empfehlenswertes Vorgehen beim Nachbauen der HW und Verwenden der SW?

**Comment by jakiss** [comment]
Das kommt zentral auf die Vorkentnisse an.

 

Vorkentnisse im Löten sind für die Montage sinnvoll.

 

Die Software kann auf zwei verschiedenen Weisen installiert werden, entweder kann ein Raspbian System manuell aufgesetzt werden und danach die Software der Code auf das System übertragen werden oder ein fertiges Images, welches ich gerne zur Verfügung,  kann auf die SD-Karte gespielt werden. Bei einem manuellen Aufsetzten sind Vorkenntnisse mit einem Raspberry Pi oder anderen Linux basierten Systemen erfoderlich.

 

Die Hardwareliste ist unter https://github.com/jakiss/Radmesser/blob/master/Projektbeschreibung.pdf auf den Seiten 85 (xvi) f. zu finden.

Danach wird noch die entsprechende Platine benötigt, wofür ich zeitnah die verbesserten Dateien zur Verfügung stellen werde. Diese sollte dann gefertigt werden beispielsweise bei https://jlcpcb.com/

 

Nach der Montage findet dann die Inbetriebnahme des Raspberry Pis statt.

 

Die einzelnen Schritte sind dann ab Seite 88 (xix) zu finden.

 

Wie viele Sensoren sollen nachgebaut werden?

Für individuelle Unterstützung stehe ich zur Verfügung. Bei Rückfragen bitte melden.

 
 

Gesendet: Mittwoch, 30. September 2020 um 17:36 Uhr
Von: "Uwe Keim" <notifications@github.com>
An: "jakiss/Radmesser" <Radmesser@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [jakiss/Radmesser] Bestes Vorgehen zum Nachbauen? (#1)


 

Habe Deine zwei PDFs überflogen, weil bei uns in Eislingen einer der Grünen vorgeschlagen hat, das nachzubauen.

Was wäre denn ein empfehlenswertes Vorgehen beim Nachbauen der HW und Verwenden der SW?

**Comment by UweKeim** [comment]
Danke Dir, @jakiss für Deine ausführlichen Erklärungen.

Habe Elektrotechnik in Esslingen studiert (auch wenn das schon 20 Jahre her ist) und bin selbst Softwareentwickler.

Ich denke, ich komme damit insgesamt schon klar.

Wir wollen das wohl im neuen Jahr mal angehen, da werde ich mich tiefer reingraben und mal schauen wie weit ich komme.

In jedem Fall ein super Projekt von Dir. Hätten wir in Deutschland keine https://mordstreifen.de sondern echte _Protected Bike Lanes_, wäre das natürlich um Welten besser, aber das ist ein ganz anderes, politisches Thema.
